# Generated by Django 3.2.23 on 2024-03-28 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Staff', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='price_list',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='price_list_applied',
        ),
    ]
